### ISSUE TITLE
Not Receiving Notification 

### ISSUE THREAD

**Issue by derycklong** [CanglongCl/Genshin-Pizza-Helper#1]
Genshin Pizza v2.4.4
iOS 16.1 beta 4

Widget added to home screen.
Notification turned on on Genshin Pizza
Notification permission granted.

**Comment by CanglongCl** [comment]
Hello, 

Thanks for your feedback. 

We also notice the problem but we still did not find out why it happens. We will keep working on it but the fix may not come in next version. 

Regards, 

Genshin Pizza Helper Developer
Lava
