### ISSUE TITLE
2.5.0更新App后在iPad OS 14.7.1上Widget失效

### ISSUE THREAD

**Issue by wudifeixue** [CanglongCl/Genshin-Pizza-Helper#2]
在更新App到2.5.0后，2.5.0更新后在iPad OS 14.7.1上Widget失效。
我的设备是M1 11寸 iPad Pro。

错误表现是旧的Widget永久性卡死在过期数据上，重新删除再创建Widget会完全一片漆黑的一个方块。
打开App内部一切账号内容显示正常。

上一个版本还可以完全正常使用，现在不能用了，正想着办法降级中。
由于完全不想更新iPad OS到新版本，比较希望可以修复iPad OS 14的这个问题。

**Comment by wudifeixue** [comment]
干，看来降级不下去，我没有版本ID信息
https://zhuanlan.zhihu.com/p/136952051
根据这个教程来的
https://tools.lancely.tech/apple/app-history
这里没有Genshin Pizza Helper 2.4.4的版本ID

爱思助手也没有发现此应用的历史版本，有点束手无策了

**Comment by wudifeixue** [comment]
我总不能自己搞台Mac..装上Xcode全家桶，再通过源码的2.4.4版本，自己build一个ipa吧...

**Comment by CanglongCl** [comment]
您好，2.5其实没有动小组件相关源码。您可以尝试重启设备重装app等方法解决。如果您需要降级，可以到我们测试群706493226 ，tf上还保留有各版本的安装包。

**Comment by wudifeixue** [comment]
谢谢，按照你说的办法确实已经解决了问题，看来这是个神奇的升级会出现的怪bug，应用本身2.5.0组件（Widget）部分并无问题。
