### ISSUE TITLE
Pizza Helper exit unexpectedly on macOS

### ISSUE THREAD

**Issue by taumasyang** [CanglongCl/Genshin-Pizza-Helper#3]
<img width="1112" alt="crush report" src="https://user-images.githubusercontent.com/39393816/204283234-a17bcd32-46a6-4cf1-8695-555f64a33364.png">
You can get basic information from the snapshot above. Tell me if you need the full report.

**Comment by CanglongCl** [comment]
Thank you for you feedback. We have fix it in the latest version (v2.7.1). It is recommended to update it. The previous version is 'made for iPad' version. The latest one has supported macOS natively. So you may have to delete the existed one and re-download it.

**Comment by taumasyang** [comment]
As you can see from the report, I have installed the 2.7.1 version. Furthermore, I cleaned all the app data, caches, etc. before reinstalling the app. It turns out still crushes.

**Comment by CanglongCl** [comment]
> As you can see from the report, I have installed the 2.7.1 version. Furthermore, I cleaned all the app data, caches, etc. before reinstalling the app. It turns out still crushes.

Emmm. Well it could be an unknown issue. When was the crush happened? When you started the app or when you were doing something else?

**Comment by taumasyang** [comment]
It all worked fine on the former 'Made for iPad' version, but began to crush days ago from v2.7.0, which supports Dynamic Island and Live Activity. I simply clicked on the widget or icon form Dock to start the app, but the icon jumped once before a crush report showed up.

**Comment by taumasyang** [comment]
It seems the app conflicts with 'Magnet'. It starts working after I quit Magnet.
<img width="460" alt="Magnet" src="https://user-images.githubusercontent.com/39393816/204287182-2f01c015-40bc-4a80-914c-708f77f81b46.png">
(The culprit)

**Comment by CanglongCl** [comment]
> It seems the app conflicts with 'Magnet'. It starts working after I quit Magnet.
> <img alt="Magnet" width="460" src="https://user-images.githubusercontent.com/39393816/204287182-2f01c015-40bc-4a80-914c-708f77f81b46.png">
> (The culprit)

Although I can't see the pic you send. That's great. Enjoy the app. 

But my partner said that he has not encountered the some issue despite that he is using magnet on his Mac as well. 

If you have any further problem encountered, feel free to contact us. Also you can join our QQ group where there is a test group where you may enjoy our beta features. 

Lava.
