### ISSUE TITLE
Crashing non stop after connecting our hoyolab account with iOS 16.0

### ISSUE THREAD

**Issue by koawaa** [CanglongCl/Genshin-Pizza-Helper#4]
Edit : now crashing almost immediatly after allowing the notifications I guess ?
As I said, it started crashing after connecting my account for first time

https://youtube.com/shorts/tCg60ysnstg

**Comment by Bill-Haku** [comment]
can you provide a screen record video for us?

**Comment by koawaa** [comment]
> Edit : now crashing almost immediatly after allowing the notifications I guess ?
> 
> https://youtube.com/shorts/tCg60ysnstg

**Comment by Bill-Haku** [comment]
Ummm that looks strange. Can you tell me your device OS version, system region and language?. BTW, can you try opening the app without connecting to the internet? It may help us locate the problem.

**Comment by koawaa** [comment]
Looks like it works fine without being connected to Internet.

Version : iOS 16.0 (20A362)
Region : France
Language : Français / French

**Comment by Bill-Haku** [comment]
Thanks for your information. We have located this issue. Can you tell me how to translate " \<name\>'s weekly boss resin discount left \<number\> times. " in French?

One thing should be pointed out is that \<name\> should appear in front of \<number\>.

**Comment by koawaa** [comment]
Ummh to be honest that's not really clear for me but it should be something like that : "< number > réduction de résine restante pour le boss hebdomadaire < name >."
Or
"Réduction de résine pour le boss hebdomadaire < name > : < number > fois."

**Comment by CanglongCl** [comment]
Thanks for your feedback. We will fix it next version. You can switch to English in your <Setting> app -> <GI Pizza> to avoid this now.
