### ISSUE TITLE
Widgets doesnt Appear on lockscreen

### ISSUE THREAD

**Issue by CustomIcon** [CanglongCl/Genshin-Pizza-Helper#6]
After the update 2.8.2 i noticed my widgets disappeared
![image](https://github.com/CanglongCl/Genshin-Pizza-Helper/assets/43902347/90725651-99ee-4502-9064-32e1091010ee)
reinstalling the app or removing/adding back the widgets did not change the fact widgets disappeared

**Comment by CustomIcon** [comment]
![image](https://github.com/CanglongCl/Genshin-Pizza-Helper/assets/43902347/2d94ae28-1756-4d0b-96ac-73973e60d382)
After updating to iOS 16.5 beta and playing around app settings it seems to have changed but values were not updating the widget

**Comment by CanglongCl** [comment]
t> ![image](https://github.com/CanglongCl/Genshin-Pizza-Helper/assets/43902347/2d94ae28-1756-4d0b-96ac-73973e60d382)
> After updating to iOS 16.5 beta and playing around app settings it seems to have changed but values were not updating the widget

Try restart the iPhone? This situation usually happened because system bug after upgrade ios.

**Comment by CustomIcon** [comment]
Issue was fixed after updating to dev beta 3 of iOS 16.5. so strange that this affected the only widgets i had on my lockscreen
